services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: "pratmat-website-local"
    environment:
      NODE_ENV: development
      NODE_PORT: 3000
      DB_USER: nodejs
      DB_HOST: db
      DB: matprat
      DB_PASSWORD: nodejs
      DB_PORT: 5432
    ports:
      - 3001:3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    volumes:
      # Mount source code for live development
      - ./server:/usr/src/app
    depends_on:
      - db

  db:
    image: postgres:14.1-alpine3.15
    restart: unless-stopped
    container_name: "pratmat-db-local"
    volumes:
      - pratmat-data-local:/var/lib/postgresql/data
      - ./database/sql:/docker-entrypoint-initdb.d:ro
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data
    ports:
      - 5433:5432

  pgadmin:
    image: dpage/pgadmin4:6.2
    restart: unless-stopped
    container_name: "pratmat-db-manager-local"
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: SuperSecret
      PGADMIN_LISTEN_PORT: 80
    depends_on:
      - db

volumes:
  pratmat-data-local:
